# Generated by Django 2.0.3 on 2018-03-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyword', models.CharField(max_length=128)),
                ('directId', models.CharField(max_length=128)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidder.Campaign')),
            ],
        ),
    ]
