# Generated by Django 2.0.3 on 2018-03-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0002_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='eyword',
            new_name='keyword',
        ),
    ]
