# Generated by Django 2.0.3 on 2018-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0003_auto_20180308_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='bid',
            field=models.CharField(default=1000, max_length=128),
            preserve_default=False,
        ),
    ]
